Repository andela/heimdal-ah-frontend, pull requests merged in 2019-02, with the labels that each got.

#32 #162170989 Articles tag
  src/component/Pages/Article/__snapshots__/ArticlePage.spec.jsx.snap
  src/component/Pages/HomePage.jsx
  src/component/Pages/articles/ReadSingleArticle/__snapshots__/ReadSingleArticle.spec.jsx.snap
  src/component/ui/Tags/ArticlesTag.jsx
  src/component/ui/Tags/ArticlesTag.scss
  src/component/ui/Tags/ArticlesTag.spec.jsx
Labels: ready, review

#25 #162170994 Search articles
  package-lock.json
  package.json
  src/actions/SearchArticles/searchArticlesByAuthorActions.js
  src/actions/SearchArticles/searchArticlesByAuthorActions.spec.js
  src/actions/SearchArticles/searchArticlesByTagsActions.js
  src/actions/SearchArticles/searchArticlesByTagsActions.spec.js
  src/actions/SearchArticles/searchArticlesByTitleActions.js
  src/actions/SearchArticles/searchArticlesByTitleActions.spec.js
  src/actions/actionTypes.js
  src/component/Pages/PasswordResetPage/PasswordReset.jsx
  src/component/ui/footer/footer.scss
  src/component/ui/header/Header.jsx
  src/component/ui/searchForm/SearchArticles.jsx
  src/component/ui/searchForm/SearchArticles.scss
  src/component/ui/searchForm/SearchArticles.spec.jsx
  src/component/ui/searchForm/__snapshots__/SearchArticles.spec.jsx.snap
  src/component/ui/searchForm/searchArticlesPresentation.js
  src/component/ui/searchForm/searchView.jsx
  src/index.html
  src/reducers/SearchArticles/searchArticlesByAuthorReducer.js
  src/reducers/SearchArticles/searchArticlesByAuthorReducer.spec.js
  src/reducers/SearchArticles/searchArticlesByTagReducer.spec.js
  src/reducers/SearchArticles/searchArticlesByTagsReducer.js
  src/reducers/SearchArticles/searchArticlesByTitleReducer.js
  src/reducers/SearchArticles/searchArticlesByTitleReducer.spec.js
  src/reducers/index.js
  src/reducers/rootReducer.js
  src/routes/routes.jsx
  src/styles/variables.scss
Labels: ready, review

#16 #162170991 Implement follow user feature
  .DS_Store
  package.json
  src/App.jsx
  src/App.spec.jsx
  src/__mocks__/fileMocks.js
  src/__snapshots__/App.spec.jsx.snap
  src/actions/actionTypes.js
  src/actions/profile/profileActions.js
  src/component/Pages/LoginPage.jsx
  src/component/Pages/PasswordResetPage/PasswordResetComponent.spec.jsx
  src/component/Pages/PasswordResetPage/__snapshots__/PasswordResetComponent.spec.jsx.snap
  src/component/Pages/Profile/Profile.jsx
  src/component/Pages/articles/ReadSingleArticle/__snapshots__/ReadSingleArticle.spec.jsx.snap
  src/component/Pages/articles/UpdateArticles/__snapshots__/UpdateArticles.spec.jsx.snap
  src/component/Pages/articles/createArticle/__snapshots__/CreateArticle.spec.jsx.snap
  src/component/ui/Alert/__snapshots__/Alert.spec.jsx.snap
  src/component/ui/Buttons/glow/__snapshots__/Glow.spec.jsx.snap
  src/component/ui/Forms/Signup/__snapshots__/Signup.spec.jsx.snap
  src/component/ui/Forms/Signup/__snapshots__/SignupForm.spec.jsx.snap
  src/component/ui/InputElements/__snapshots__/FormInput.spec.jsx.snap
  src/component/ui/Rating/__snapshots__/ArticlesRatings.spec.jsx.snap
  src/component/ui/cards/__snapshots__/Cards.spec.jsx.snap
  src/component/ui/errors/__snapshots__/MainError.spec.jsx.snap
  src/component/ui/footer/__snapshots__/footer.spec.jsx.snap
  src/component/ui/header/__snapshots__/Header.spec.jsx.snap
  src/component/ui/loadingSpinners/__snapshots__/LoadingSpinner.spec.jsx.snap
  src/container/Profile/ProfileContainer.js
  src/container/__snapshots__/AuthContainer.spec.jsx.snap
  src/reducers/profile/profileReducer.js
  src/reducers/rootReducer.js
Labels: review

#26 #162171000 add comment edit history functionality
  package-lock.json
  src/actions/CommentEditHistory/CommentEditHistory.js
  src/actions/actionTypes.js
  src/component/ui/CommentCard/CommentCard.jsx
  src/component/ui/CommentEditHistory/CommentEditHistory.jsx
  src/component/ui/CommentEditHistory/CommentEditHistory.scss
  src/component/ui/Elllipse/Ellipse.jsx
  src/component/ui/Elllipse/Ellipse.scss
  src/component/ui/Elllipse/Ellipse.spec.js
  src/component/ui/Elllipse/__snapshots__/Ellipse.spec.js.snap
  src/component/ui/Modal/Index.jsx
  src/component/ui/Modal/__snapshots__/TriggerModal.spec.jsx.snap
  src/component/ui/headerButton/HeaderButton.jsx
  src/reducers/CommentHistoryReducer/CommentHistoryReducer.js
  src/reducers/CommentHistoryReducer/CommentHistoryReducer.spec.js
  src/reducers/CommentHistoryReducer/__snapshots__/CommentHistoryReducer.spec.js.snap
  src/reducers/rootReducer.js
  src/routes/routes.jsx
  src/styles/variables.scss
Labels: review

#35 #162170988 article glow functionality
  src/actions/ArticleActions/getArticlesByIdActions.jsx
  src/actions/ArticleActions/getArticlesByIdActions.spec.js
  src/actions/actionTypes.js
  src/actions/auth/logout.js
  src/component/Pages/articles/ReadSingleArticle/ReadSingleArticle.jsx
  src/component/Pages/articles/ReadSingleArticle/ReadSingleArticlePresentation.jsx
  src/component/Pages/articles/ReadSingleArticle/__snapshots__/ReadSingleArticle.spec.jsx.snap
  src/component/Pages/articles/UpdateArticles/UpdateArticles.jsx
  src/component/Pages/articles/UpdateArticles/UpdateArticles.spec.jsx
  src/component/ui/Buttons/glow/Glow.jsx
  src/component/ui/activeuser/ActiveUser.jsx
  src/component/ui/cards/ArticleCard/ArticleCard.jsx
  src/component/ui/header/Header.jsx
  src/reducers/articlesReducers/getArticlesByIdReducer.js
Labels: ready, review

#38 #163486625 End to end test
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/commentEditHistory.specx.js
  cypress/integration/commentOnArticle.specx.js
  cypress/integration/editProfile.specx.js
  cypress/integration/followUser.specx.js
  cypress/integration/landingPage.specx.js
  cypress/integration/listArticles.specx.js
  cypress/integration/rateArticles.specx.js
  cypress/integration/reportArticle.specx.js
  cypress/integration/resetPassword.specx.js
  cypress/integration/searchArticles.specx.js
  cypress/integration/signin.specx.js
  cypress/integration/signup.specx.js
  cypress/plugins/index.js
  cypress/screenshots/editProfile.spec.js/Edit user Profile -- .should() - visit heimdal home page, login and navigate to profile and click the edit button (failed).png
  cypress/support/commands.js
  cypress/support/index.js
  cypress/videos/commentEditHistory.spec.js.mp4
  cypress/videos/commentOnArticle.spec.js.mp4
  cypress/videos/editProfile.spec.js-compressed.mp4
  cypress/videos/editProfile.spec.js.mp4
  jest.config.js
  package-lock.json
  package.json
  src/actions/ArticleActions/articleAction.spec.js
  src/actions/ArticleActions/articles.js
  src/actions/PasswordReset/resetPasswordActions.js
  src/component/ui/Buttons/Button.jsx
  src/component/ui/searchForm/searchArticlesPresentation.jsx
  src/component/ui/searchForm/searchView.jsx
Labels: ready

#42 Ft pagination support for articles 162170987
  package-lock.json
  package.json
  src/__mocks__/articleMocks.js
  src/actions/ArticleActions/articleAction.spec.js
  src/actions/ArticleActions/articles.js
  src/actions/actionTypes.js
  src/actions/articleActions/articleAction.spec.js
  src/actions/articleActions/articles.js
  src/component/Pages/Article/ArticleListPage.jsx
  src/component/Pages/Article/article.css
  src/component/Pages/articles/ReadSingleArticle/ReadSingleArticlePresentation.jsx
  src/component/ui/Buttons/glow/Glow.scss
  src/component/ui/activeuser/ActiveUser.jsx
  src/component/ui/logo/Logo.jsx
  src/component/ui/searchForm/SearchArticles.jsx
  src/container/Article/Article.js
  src/reducers/Article/articleReducer.js
  src/styles/global.scss
Labels: WIP

#44 #163719285 populate returned searched articles into cards
  package-lock.json
  src/component/ui/searchForm/SearchArticles.scss
  src/component/ui/searchForm/searchView.jsx
Labels: ready

#48 #163797500 update [reset password, update password, edit article] pages
  package-lock.json
  src/component/Pages/PasswordResetPage/PasswordReset.jsx
  src/component/Pages/PasswordResetPage/PasswordReset.scss
  src/component/Pages/PasswordResetPage/PasswordResetPresentation.jsx
  src/component/Pages/PasswordResetPage/UpdatePassword.jsx
  src/component/Pages/PasswordResetPage/UpdatePasswordPresentation.jsx
  src/component/Pages/articles/UpdateArticles/UpdateArticles.scss
  src/component/Pages/articles/UpdateArticles/UpdateArticlesPresentation.jsx
Labels: ready

#49 [#163801826] fix jumping footer
  package-lock.json
  src/actions/auth/signin.js
  src/component/Layout/MainLayout/mainLayout.scss
  src/component/Pages/Article/ArticleListPage.jsx
  src/component/Pages/Article/__snapshots__/ArticlePage.spec.jsx.snap
  src/component/Pages/articles/ReadSingleArticle/__snapshots__/ReadSingleArticle.spec.jsx.snap
  src/component/ui/Comment/__snapshots__/Comment.spec.jsx.snap
  src/component/ui/Forms/Signin/SignInForm.jsx
  src/component/ui/Forms/Signin/SignInForm.spec.jsx
  src/component/ui/Forms/Signin/__snapshots__/SignInForm.spec.jsx.snap
  src/component/ui/Forms/Signup/Signup.jsx
  src/component/ui/Forms/Signup/SignupForm.jsx
  src/component/ui/Forms/Signup/__snapshots__/SignupForm.spec.jsx.snap
  src/component/ui/InputElements/FormInput.jsx
  src/container/Article/Article.js
  src/container/AuthContainer.jsx
  src/container/__snapshots__/AuthContainer.spec.jsx.snap
  src/styles/global.scss
Labels: WIP
