Repository andela/heimdal-ah-frontend, pull requests merged in 2019-01, with the labels that each got.

#3 #162170978 Setup Codeclimate
  .eslintrc
  .gitignore
  .travis.yml
  README.md
  coverage/base.css
  coverage/index.html
  coverage/lcov-report/base.css
  coverage/lcov-report/index.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov.info
  coverage/prettify.css
  coverage/prettify.js
  coverage/sort-arrow-sprite.png
  coverage/sorter.js
  jest.config.js
  package-lock.json
  package.json
  src/App.spec.jsx
  src/__snapshots__/App.spec.jsx.snap
  src/component/UI/buttons/HomePageButton.spec.jsx
Labels: review

#7 163152252 create button component
  .gitignore
  enzyme.config.js
  package-lock.json
  src/component/Pages/HomePage.jsx
  src/component/Pages/LoginPage.jsx
  src/component/UI/buttons/Button.jsx
  src/component/UI/buttons/Button.spec.jsx
  src/component/UI/buttons/ButtonStyles.scss
  src/component/UI/buttons/HomePageButton.spec.jsx
  src/component/UI/buttons/HomepageButton.jsx
  src/component/UI/buttons/LoginButton.jsx
  src/index.html
Labels: ready

#10 #163166708 create rating component
  .eslintrc
  package-lock.json
  package.json
  src/App.jsx
  src/component/Pages/HomePage.jsx
  src/component/Pages/LoginPage.jsx
  src/component/ui/Rating/Rating.jsx
  src/component/ui/Rating/Rating.scss
  src/component/ui/Rating/Rating.spec.jsx
  src/component/ui/buttons/.DS_Store
  src/component/ui/buttons/Button.jsx
  src/component/ui/buttons/Button.spec.jsx
  src/component/ui/buttons/ButtonStyles.scss
  src/component/ui/buttons/glow/DemoArticleCoponentWithGlowState.jsx
  src/component/ui/buttons/glow/Glow.jsx
  src/component/ui/buttons/glow/Glow.scss
  src/component/ui/buttons/glow/Glow.spec.jsx
  src/component/ui/buttons/glow/__snapshots__/Glow.spec.jsx.snap
  src/index.jsx
  src/styles/globals.scss
  webpack.common.js
Labels: ready

#9 #163164096 Create footer component
  package-lock.json
  package.json
  src/App.jsx
  src/component/Layout/Layout.jsx
  src/component/ui/buttons/ButtonStyles.scss
  src/component/ui/footer/Footer.jsx
  src/component/ui/footer/__snapshots__/footer.spec.jsx.snap
  src/component/ui/footer/footer.scss
  src/component/ui/footer/footer.spec.jsx
  src/styles/global.scss
  src/styles/globals.scss
  src/styles/variables.scss
Labels: WIP, review

#12 #163155405 create content layout component
  src/component/Layout/MainLayout/MainLayout.jsx
  src/component/Layout/MainLayout/MainLayout.spec.jsx
  src/routes/routes.jsx
Labels: ready, review

#13 Ft cards component #163217557
  .babelrc
  README.md
  helper/cardsHelper.js
  package-lock.json
  src/component/Pages/HomePage.jsx
  src/component/Widgets/.DS_Store
  src/component/ui/Rating/Rating.jsx
  src/component/ui/Rating/Rating.scss
  src/component/ui/buttons/.DS_Store
  src/component/ui/buttons/glow/Glow.jsx
  src/component/ui/buttons/glow/Glow.scss
  src/component/ui/buttons/glow/__snapshots__/Glow.spec.jsx.snap
  src/component/ui/cards/ArticleCardHorizontal.jsx
  src/component/ui/cards/ArticleCardVertical.jsx
  src/component/ui/cards/BookmarksCards.jsx
  src/component/ui/cards/Cards.spec.jsx
  src/component/ui/cards/__snapshots__/Cards.spec.jsx.snap
  src/component/ui/cards/articleCardHorizontal.scss
  src/component/ui/cards/articleCardVertical.scss
  src/component/ui/cards/bookmarksCards.scss
  src/images/bookmark.svg
  src/routes/routes.jsx
Labels: review

#14 #162170980 reset users password
  .DS_Store
  .env_samples
  enzyme.config.js
  package-lock.json
  package.json
  src/actions/PasswordReset/resetPasswordActions.js
  src/actions/PasswordReset/resetPasswordActions.spec.js
  src/actions/PasswordReset/updatePasswordActions.js
  src/actions/PasswordReset/updatePasswordActions.spec.js
  src/actions/actionResponse.js
  src/actions/actionTypes.js
  src/component/Pages/HomePage.jsx
  src/component/Pages/LoginPage.jsx
  src/component/Pages/PasswordResetPage/PasswordReset.jsx
  src/component/Pages/PasswordResetPage/PasswordReset.scss
  src/component/Pages/PasswordResetPage/PasswordResetComponent.spec.jsx
  src/component/Pages/PasswordResetPage/PasswordResetPresentation.jsx
  src/component/Pages/PasswordResetPage/UpdatePassword.jsx
  src/component/Pages/PasswordResetPage/UpdatePasswordPresentation.jsx
  src/component/Pages/PasswordResetPage/__snapshots__/PasswordResetComponent.spec.jsx.snap
  src/component/Widgets/headerButton/HeaderButton.jsx
  src/component/ui/Alert/Alert.jsx
  src/component/ui/Alert/Alert.spec.jsx
  src/component/ui/Alert/__snapshots__/Alert.spec.jsx.snap
  src/component/ui/Buttons/.DS_Store
  src/component/ui/Buttons/Button.jsx
  src/component/ui/Buttons/Button.spec.jsx
  src/component/ui/Buttons/ButtonStyles.scss
  src/component/ui/Buttons/glow/DemoArticleCoponentWithGlowState.jsx
  src/component/ui/Buttons/glow/Glow.jsx
  src/component/ui/Buttons/glow/Glow.scss
  src/component/ui/Buttons/glow/Glow.spec.jsx
  src/component/ui/Buttons/glow/__snapshots__/Glow.spec.jsx.snap
  src/component/ui/cards/ArticleCardHorizontal.jsx
  src/component/ui/cards/ArticleCardVertical.jsx
  src/component/ui/cards/BookmarksCards.jsx
  src/component/ui/header/Header.spec.jsx
  src/config/http.js
  src/index.html
  src/reducers/PasswordReset/ResetPasswordReducer.spec.js
  src/reducers/PasswordReset/UpdatePasswordReducer.spec.js
  src/reducers/PasswordReset/resetPasswordReducer.js
  src/reducers/PasswordReset/updatePasswordReducer.js
  src/reducers/index.js
  src/reducers/rootReducer.js
  src/routes/routes.jsx
  src/store/configureStore.js
  src/styles/variables.scss
  webpack.common.js
Labels: ready

#19 #162170982 social Authentication
  .DS_Store
  jest.config.js
  package-lock.json
  package.json
  src/actions/SocialAuthActions/socialAuth.js
  src/actions/SocialAuthActions/socialAuthAction.spec.js
  src/actions/actionTypes.js
  src/component/Layout/Layout.jsx
  src/component/Layout/Layout.spec.js
  src/component/Layout/MainLayout/MainLayout.jsx
  src/component/Pages/HomePage.jsx
  src/component/Pages/LoginPage.jsx
  src/component/Widgets/searchForm/SearchForm.scss
  src/component/ui/SocialAuth/SocialAuth.jsx
  src/component/ui/SocialAuth/socialAuth.spec.jsx
  src/component/ui/activeuser/ActiveUser.jsx
  src/component/ui/activeuser/ActiveUser.spec.js
  src/component/ui/cards/ArticleCardHorizontal.jsx
  src/component/ui/header/Header.jsx
  src/component/ui/header/Header.spec.jsx
  src/component/ui/header/__snapshots__/Header.spec.jsx.snap
  src/component/ui/headerButton/HeaderButton.jsx
  src/component/ui/headerButton/HeaderButton.spec.js
  src/component/ui/headerButton/__snapshots__/HeaderButton.spec.js.snap
  src/component/ui/searchForm/SearchForm.jsx
  src/component/ui/searchForm/SearchForm.scss
  src/component/ui/searchForm/SearchForm.spec.jsx
  src/config/http.js
  src/config/setToken.js
  src/index.jsx
  src/reducers/SocialAuthReducer/SocialAuthReducer.spec.js
  src/reducers/SocialAuthReducer/__snapshots__/SocialAuthReducer.spec.js.snap
  src/reducers/SocialAuthReducer/socialAuthReducer.js
  src/reducers/rootReducer.js
  src/routes/routes.jsx
  src/utils/isEmpty.js
  webpack.common.js
  webpack.dev.js
Labels: review

#24 #162170980 fix password field and clearing email during password reset
  package-lock.json
  src/component/Pages/PasswordResetPage/PasswordReset.jsx
  src/component/Pages/PasswordResetPage/PasswordResetPresentation.jsx
  src/component/Pages/PasswordResetPage/UpdatePasswordPresentation.jsx
  src/config/http.js
  src/routes/routes.jsx
Labels: ready

#18 #162170981 add login functionality
  helper/cardsHelper.js
  package-lock.json
  package.json
  src/actions/actionTypes.js
  src/actions/auth/signin.js
  src/actions/auth/signin.spec.js
  src/component/Pages/LoginPage.jsx
  src/component/ui/Forms/Signin/SignInForm.jsx
  src/component/ui/Forms/Signin/SignInForm.spec.jsx
  src/component/ui/Forms/Signin/Signin.scss
  src/component/ui/Forms/Signin/__snapshots__/SignInForm.spec.jsx.snap
  src/component/ui/InputElements/FormInput.jsx
  src/component/ui/Modal/Index.jsx
  src/component/ui/Modal/TriggerModal.scss
  src/component/ui/Modal/__snapshots__/TriggerModal.spec.jsx.snap
  src/component/ui/errors/SignInError.jsx
  src/component/ui/errors/SignInError.spec.jsx
  src/component/ui/errors/__snapshots__/SignInError.spec.jsx.snap
  src/component/ui/headerButton/HeaderButton.jsx
  src/component/ui/headerButton/HeaderButton.spec.jsx
  src/component/ui/headerButton/__snapshots__/HeaderButton.spec.jsx.snap
  src/config/http.js
  src/container/AuthContainer.jsx
  src/container/AuthContainer.spec.jsx
  src/container/__snapshots__/AuthContainer.spec.jsx.snap
  src/helpers/validateInputs.js
  src/reducers/AuthReducer/__snapshots__/auth.spec.js.snap
  src/reducers/AuthReducer/auth.js
  src/reducers/AuthReducer/auth.spec.js
  src/reducers/rootReducer.js
  src/routes/routes.jsx
  src/styles/global.scss
Labels: review

#21 #162170985 users rating on articles
  src/actions/ArticlesRating/articlesRating.js
  src/actions/ArticlesRating/articlesRating.spec.js
  src/actions/ArticlesRating/getArticlesRating.js
  src/actions/ArticlesRating/getArticlesRating.spec.js
  src/actions/actionTypes.js
  src/actions/auth/signin.js
  src/component/ui/Rating/ArticlesRating.jsx
  src/component/ui/Rating/ArticlesRatings.spec.jsx
  src/component/ui/Rating/Rating.scss
  src/component/ui/Rating/__snapshots__/ArticlesRatings.spec.jsx.snap
  src/reducers/ArticlesRating/articlesRatingReducer.js
  src/reducers/ArticlesRating/articlesRatingReducer.spec.js
  src/reducers/ArticlesRating/getArticlesRating.spec.js
  src/reducers/ArticlesRating/getArticlesRatingReducer.js
  src/reducers/authReducer.js
  src/reducers/index.js
  src/reducers/rootReducer.js
  src/utils/getAverageRatings.js
Labels: review

#30 #163486215 Creates Article list page
  .eslintrc
  package.json
  src/__mocks__/articleMocks.js
  src/actions/ArticleActions/articleAction.spec.js
  src/actions/ArticleActions/articles.js
  src/actions/actionTypes.js
  src/component/Pages/Article/ArticleListPage.jsx
  src/component/Pages/Article/ArticlePage.spec.jsx
  src/component/Pages/Article/__snapshots__/ArticlePage.spec.jsx.snap
  src/component/ui/cards/ArticleCard/articleCard.scss
  src/container/Article/Article.js
  src/reducers/Article/articleReducer.js
  src/reducers/Article/articleReducer.spec.js
  src/reducers/index.js
  src/reducers/rootReducer.js
  src/routes/routes.jsx
Labels: ready
